language: java
jdk:
  - oraclejdk17

before_install:
  - chmod +x gradlew

install: skip

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email:
recipients:
  - viniciuscbrito89@gmail.com
on_success: always
on_failure: always
