spring:
  datasource:
    url: jdbc:mysql://localhost:3307/school_registration_db?useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  port: 6868