spring:
  datasource:
    url: jdbc:mysql://localhost:3307/school_registration_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
server:
  port: 6868
flyway:
  url: jdbc:mysql://localhost:3307/school_registration_db?createDatabaseIfNotExist=true&useSSL=false
  user: root
  password: 123456